from typing import List, Dict, Any

FEATURES: List[Dict[str, Any]] = [
    # Domain A: Price & Volume
    {
        "feature_name": "ret_cc_1d",
        "domain": "A",
        "source_table": "daily",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "close, pre_close",
        "formula_desc": "close/pre_close - 1",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "clip_1_99",
        "neutralize_policy": "none",
        "start_date": "",
        "notes": "Daily close-to-close return"
    },
    {
        "feature_name": "ret_oc_1d",
        "domain": "A",
        "source_table": "daily",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "close, open",
        "formula_desc": "close/open - 1",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "",
        "notes": "Intraday return (Open to Close)"
    },
    {
        "feature_name": "gap_open",
        "domain": "A",
        "source_table": "daily",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "open, pre_close",
        "formula_desc": "open/pre_close - 1",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "clip_1_99",
        "neutralize_policy": "none",
        "start_date": "",
        "notes": "Overnight gap"
    },
    {
        "feature_name": "intraday_range",
        "domain": "A",
        "source_table": "daily",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "high, low, pre_close",
        "formula_desc": "(high-low)/(pre_close + epsilon)",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "clip_1_99",
        "neutralize_policy": "none",
        "start_date": "",
        "notes": "True range normalized"
    },
    {
        "feature_name": "upper_shadow_ratio",
        "domain": "A",
        "source_table": "daily",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "high, open, close, low",
        "formula_desc": "(high-max(open,close))/(high-low+epsilon)",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "",
        "notes": "Upper shadow strength"
    },
    {
        "feature_name": "lower_shadow_ratio",
        "domain": "A",
        "source_table": "daily",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "high, open, close, low",
        "formula_desc": "(min(open,close)-low)/(high-low+epsilon)",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "",
        "notes": "Lower shadow strength"
    },
    {
        "feature_name": "turnover_free",
        "domain": "A",
        "source_table": "daily_basic",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "turnover_rate_f",
        "formula_desc": "turnover_rate_f / 100",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "none",
        "neutralize_policy": "optional_cs",
        "start_date": "",
        "notes": "Free float turnover rate"
    },
    {
        "feature_name": "volume_ratio_ln",
        "domain": "A",
        "source_table": "daily_basic",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "volume_ratio",
        "formula_desc": "log(1 + volume_ratio)",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "none",
        "neutralize_policy": "optional_cs",
        "start_date": "",
        "notes": "Log volume ratio"
    },
    
    # Domain B: Moneyflow
    {
        "feature_name": "imb_sm_amt",
        "domain": "B",
        "source_table": "moneyflow",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "buy_sm_amount, sell_sm_amount",
        "formula_desc": "(buy_sm - sell_sm) / (buy_sm + sell_sm + eps)",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "zero_if_both_zero_else_nan",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "20100101",
        "notes": "Small order imbalance"
    },
    {
        "feature_name": "imb_md_amt",
        "domain": "B",
        "source_table": "moneyflow",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "buy_md_amount, sell_md_amount",
        "formula_desc": "(buy_md - sell_md) / (buy_md + sell_md + eps)",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "zero_if_both_zero_else_nan",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "20100101",
        "notes": "Medium order imbalance"
    },
    {
        "feature_name": "imb_lg_amt",
        "domain": "B",
        "source_table": "moneyflow",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "buy_lg_amount, sell_lg_amount",
        "formula_desc": "(buy_lg - sell_lg) / (buy_lg + sell_lg + eps)",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "zero_if_both_zero_else_nan",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "20100101",
        "notes": "Large order imbalance"
    },
    {
        "feature_name": "imb_elg_amt",
        "domain": "B",
        "source_table": "moneyflow",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "buy_elg_amount, sell_elg_amount",
        "formula_desc": "(buy_elg - sell_elg) / (buy_elg + sell_elg + eps)",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "zero_if_both_zero_else_nan",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "20100101",
        "notes": "Extra large order imbalance"
    },
    {
        "feature_name": "net_mf_to_amount",
        "domain": "B",
        "source_table": "moneyflow, daily",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "net_mf_amount, amount",
        "formula_desc": "net_mf_amount / (amount + eps)",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "nan_if_amount_zero",
        "clip_policy": "clip_1_99",
        "neutralize_policy": "optional_cs",
        "start_date": "20100101",
        "notes": "Net moneyflow ratio. Note unit conversion needed."
    },
    {
        "feature_name": "large_buy_share",
        "domain": "B",
        "source_table": "moneyflow",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "buy_lg, buy_elg, buy_sm, buy_md",
        "formula_desc": "(lg+elg)/total_buy",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "20100101",
        "notes": "Share of large buy orders"
    },
    {
        "feature_name": "large_sell_share",
        "domain": "B",
        "source_table": "moneyflow",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "sell_lg, sell_elg, sell_sm, sell_md",
        "formula_desc": "(lg+elg)/total_sell",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "20100101",
        "notes": "Share of large sell orders"
    },
    {
        "feature_name": "flow_divergence",
        "domain": "B",
        "source_table": "moneyflow",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "imb_elg_amt, imb_sm_amt",
        "formula_desc": "imb_elg_amt - imb_sm_amt",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "20100101",
        "notes": "Divergence between ELG and Small orders"
    },
    
    # Domain C: Chip Distribution
    {
        "feature_name": "close_vs_cost50",
        "domain": "C",
        "source_table": "cyq_perf, daily",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "close, cost_50pct",
        "formula_desc": "(close - cost_50pct) / (close + eps)",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "ffill_1d_if_single_gap",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "20180101",
        "notes": "Price vs Median Cost"
    },
    {
        "feature_name": "close_vs_weight_avg",
        "domain": "C",
        "source_table": "cyq_perf, daily",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "close, weight_avg",
        "formula_desc": "(close - weight_avg) / (close + eps)",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "ffill_1d_if_single_gap",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "20180101",
        "notes": "Price vs Avg Cost"
    },
    {
        "feature_name": "chip_width_95_5",
        "domain": "C",
        "source_table": "cyq_perf, daily",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "cost_95pct, cost_5pct, close",
        "formula_desc": "(cost_95pct - cost_5pct) / (close + eps)",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "ffill_1d_if_single_gap",
        "clip_policy": "clip_1_99",
        "neutralize_policy": "none",
        "start_date": "20180101",
        "notes": "Chip distribution width (90%)"
    },
    {
        "feature_name": "chip_width_85_15",
        "domain": "C",
        "source_table": "cyq_perf, daily",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "cost_85pct, cost_15pct, close",
        "formula_desc": "(cost_85pct - cost_15pct) / (close + eps)",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "ffill_1d_if_single_gap",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "20180101",
        "notes": "Chip distribution width (70%)"
    },
    {
        "feature_name": "overhang_95",
        "domain": "C",
        "source_table": "cyq_perf, daily",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "cost_95pct, close",
        "formula_desc": "(cost_95pct - close) / (close + eps)",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "ffill_1d_if_single_gap",
        "clip_policy": "clip_1_99",
        "neutralize_policy": "none",
        "start_date": "20180101",
        "notes": "Overhead pressure"
    },
    {
        "feature_name": "support_5",
        "domain": "C",
        "source_table": "cyq_perf, daily",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "cost_5pct, close",
        "formula_desc": "(close - cost_5pct) / (close + eps)",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "ffill_1d_if_single_gap",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "20180101",
        "notes": "Support cushion"
    },
    {
        "feature_name": "winner_rate_pct",
        "domain": "C",
        "source_table": "cyq_perf",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "winner_rate",
        "formula_desc": "winner_rate / 100",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "clip_0_1",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "20180101",
        "notes": "Winner rate normalized"
    },
    {
        "feature_name": "price_pos_hist",
        "domain": "C",
        "source_table": "cyq_perf, daily",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "close, his_low, his_high",
        "formula_desc": "(close - his_low) / (his_high - his_low + eps)",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "clip_0_1_robust",
        "neutralize_policy": "none",
        "start_date": "20180101",
        "notes": "Price position in history"
    },

    # Domain D: Fundamental (Model Only)
    {
        "feature_name": "pe_ttm_rank_ind",
        "domain": "D",
        "source_table": "daily_basic",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "pe_ttm, industry",
        "formula_desc": "industry rank of pe_ttm",
        "unit_type": "rank",
        "value_type": "float",
        "allow_in_alphaprobe": 0,
        "allow_in_model": 1,
        "fill_policy": "industry_median",
        "clip_policy": "none",
        "neutralize_policy": "industry_rank",
        "start_date": "",
        "notes": "PE TTM Industry Rank"
    },
    {
        "feature_name": "pb_rank_ind",
        "domain": "D",
        "source_table": "daily_basic",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "pb, industry",
        "formula_desc": "industry rank of pb",
        "unit_type": "rank",
        "value_type": "float",
        "allow_in_alphaprobe": 0,
        "allow_in_model": 1,
        "fill_policy": "industry_median",
        "clip_policy": "none",
        "neutralize_policy": "industry_rank",
        "start_date": "",
        "notes": "PB Industry Rank"
    },
    {
        "feature_name": "ps_ttm_rank_ind",
        "domain": "D",
        "source_table": "daily_basic",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "ps_ttm, industry",
        "formula_desc": "industry rank of ps_ttm",
        "unit_type": "rank",
        "value_type": "float",
        "allow_in_alphaprobe": 0,
        "allow_in_model": 1,
        "fill_policy": "industry_median",
        "clip_policy": "none",
        "neutralize_policy": "industry_rank",
        "start_date": "",
        "notes": "PS TTM Industry Rank"
    },
    {
        "feature_name": "dv_ttm_rank_mkt",
        "domain": "D",
        "source_table": "daily_basic",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "dv_ttm",
        "formula_desc": "market rank of dv_ttm",
        "unit_type": "rank",
        "value_type": "float",
        "allow_in_alphaprobe": 0,
        "allow_in_model": 1,
        "fill_policy": "zero",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "",
        "notes": "Dividend Yield Market Rank"
    },
    {
        "feature_name": "mv_rank_mkt",
        "domain": "D",
        "source_table": "daily_basic",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "total_mv",
        "formula_desc": "market rank of total_mv",
        "unit_type": "rank",
        "value_type": "float",
        "allow_in_alphaprobe": 0,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "",
        "notes": "Total Market Value Rank"
    },
    {
        "feature_name": "free_float_ratio",
        "domain": "D",
        "source_table": "daily_basic",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "free_share, total_share",
        "formula_desc": "free_share / (total_share + eps)",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 0,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "",
        "notes": "Free Float Ratio"
    },
    {
        "feature_name": "circ_mv_to_total_mv",
        "domain": "D",
        "source_table": "daily_basic",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "circ_mv, total_mv",
        "formula_desc": "circ_mv / (total_mv + eps)",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 0,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "",
        "notes": "Circulating MV Ratio"
    },
    {
        "feature_name": "valuation_compress_score",
        "domain": "D",
        "source_table": "daily_basic",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "pe_ttm_rank, pb_rank, ps_ttm_rank",
        "formula_desc": "-0.4*pe -0.4*pb -0.2*ps",
        "unit_type": "score",
        "value_type": "float",
        "allow_in_alphaprobe": 0,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "",
        "notes": "Composite Valuation Score"
    },
    
    # Domain E: Intraday Summary
    {
        "feature_name": "hour1_ret",
        "domain": "E",
        "source_table": "stk_60_mins",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "close_h1, open_h1",
        "formula_desc": "First hour return",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "",
        "notes": "First hour return"
    },
    {
        "feature_name": "lasthour_ret",
        "domain": "E",
        "source_table": "stk_60_mins",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "close_last, open_last",
        "formula_desc": "Last hour return",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "",
        "notes": "Last hour return"
    },
    {
        "feature_name": "midday_reversal",
        "domain": "E",
        "source_table": "stk_60_mins",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "lasthour_ret, hour1_ret",
        "formula_desc": "lasthour_ret - hour1_ret",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "",
        "notes": "Intraday reversal"
    },
    {
        "feature_name": "intraday_trend_eff",
        "domain": "E",
        "source_table": "stk_60_mins",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "day_ret, sum_abs_hourly_ret",
        "formula_desc": "(close_day-open_day)/sum(|ret_h|)",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "clip_20",
        "neutralize_policy": "none",
        "start_date": "",
        "notes": "Intraday trend efficiency"
    },
    {
        "feature_name": "hourly_volatility",
        "domain": "E",
        "source_table": "stk_60_mins",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "hourly_returns",
        "formula_desc": "std(hourly_returns)",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "",
        "notes": "Hourly return volatility"
    },
    {
        "feature_name": "volume_concentration_pm",
        "domain": "E",
        "source_table": "stk_60_mins",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "vol_pm, vol_total",
        "formula_desc": "vol_pm / vol_total",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "",
        "notes": "Afternoon volume concentration"
    },
    {
        "feature_name": "vwap_close_bias_1h",
        "domain": "E",
        "source_table": "stk_60_mins",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "close, vwap_1h",
        "formula_desc": "(close - vwap_1h) / close",
        "unit_type": "ratio",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "",
        "notes": "Close vs 1H VWAP bias"
    },
    {
        "feature_name": "high_low_time_skew",
        "domain": "E",
        "source_table": "stk_60_mins",
        "freq": "daily",
        "entity_key": "ts_code",
        "time_key": "trade_date",
        "source_columns": "high_time, low_time",
        "formula_desc": "high_time_idx - low_time_idx (normalized)",
        "unit_type": "score",
        "value_type": "float",
        "allow_in_alphaprobe": 1,
        "allow_in_model": 1,
        "fill_policy": "none",
        "clip_policy": "none",
        "neutralize_policy": "none",
        "start_date": "",
        "notes": "Timing skew of high/low"
    }
]
